### ISSUE TITLE
Doesnt appear to be a working build

### ISSUE THREAD

**Issue by dtpowers** [hatboysam/JavaSnap#40]
Each time I try to log in I get I get
 Failed to log in.
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
    at org.json.JSONObject.<init>(JSONObject.java:188)
    at org.json.JSONObject.<init>(JSONObject.java:314)
    at com.habosa.javasnap.Snapchat.login(Snapchat.java:174)
    at com.habosa.javasnap.Main.main(Main.java:22)

Is this something on my end or are there still issues with JSON/Unirest

**Comment by liamcottle** [comment]
Your ip address must be blocked? In this case the server returns a 401
forbidden html page, not json.

**Comment by dtpowers** [comment]
that would make sense, and I thought of that, however when loggin in from mobile I dont get the usual ip banned message.

**Comment by Snowlav** [comment]
are you logging in from WIFI and not accidentally 3/4g ?
Proxy on your pc?

Try a free vpn if you have to and see if the same error persists to exist.

**Comment by dtpowers** [comment]
Im going to set up an ec2 instance so I can get new ip's a plenty and I will let you know how it goes

**Comment by jamesst20** [comment]
@dtpowers Was your issue fixed?

**Comment by quantum285** [comment]
Same here, but I don't have a clue why my IP address would be banned, is this usual?

**Comment by liamcottle** [comment]
This repo is extremely outdated, using old API endpoints. If you wish to use a PHP library, check out this repo as It's the most up to date. https://github.com/mgp25/Snap-API

**Comment by hatboysam** [comment]
This library has been dead for a long time, officially closing all issues.
