### ISSUE TITLE
Saving my stroys

### ISSUE THREAD

**Issue by orangelight** [hatboysam/JavaSnap#41]
When I try to save my story's it gives me java.security.InvalidKeyException: Illegal key size from the StoryEncryption class
I'm using the Main demo but instead of getting friends story's it gets mine.

**Comment by jamesst20** [comment]
Hi,

You need Java Cryptography Extension (JCE). 

You can download it here : 
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

Copy the jars inside C:\Program Files\Java\jdk1.8.0_25\jre\lib\security and C:\Program Files\Java\jre1.8.0_25\lib\security  (If it ask to overwritte, say yes).

That should fix it. You might need to link those jar as library but I don't think it is necessary. Trust me, this is not an issue inside the library

**Comment by orangelight** [comment]
Thanks it works now!

**Comment by jamesst20** [comment]
Glad I could help :)
