### ISSUE TITLE
Downloading video snaps

### ISSUE THREAD

**Issue by orangelight** [hatboysam/JavaSnap#43]
It appears that every once in while when it downloads a video snap it will save it as mp4 but the format of the file is a zip. Here is an [example](https://drive.google.com/file/d/0B5OWWAYJUsrMNnFqM3pxdGtISkk/view?usp=sharing)

**Comment by jamesst20** [comment]
Yep we are aware of that :) We just didn't code it yet

**Comment by liamcottle** [comment]
You can just check the first few bytes of the file to see if it's a ZIP or not.
https://github.com/hatboysam/JavaSnap/issues/16

**Comment by orangelight** [comment]
Thanks I look into it

**Comment by orangelight** [comment]
So that means that sending video snaps with an overlay in not supported yet

**Comment by liamcottle** [comment]
You upload the video in a zip with a png overlay that is the same
resolution as the video.

Video is media~uuid and the overlay is overlay~uuid from what I can
remember off the top of my head.

Im not at home at the moment, but if you need more info about sending
videos with/without captions/drawings let me know.

**Comment by orangelight** [comment]
I save the snap I receive as a zip but when I try to snap the zip file it fails.

**Comment by jamesst20** [comment]
Yeah it's because you must set zipped=true in the request
