### ISSUE TITLE
Friends and Friend requests

### ISSUE THREAD

**Issue by orangelight** [hatboysam/JavaSnap#44]
I don't seem to be receiving any friend requests even though I sent some to the account. Also I have added friends but when I call the getFriends method, a blank array is returned.

**Comment by jamesst20** [comment]
Hi,

I do not have time to verify that right now, however you can see if my
library on my GitHub suffer from that (QtSnap), mine should be fine.




Le mercredi 21 janvier 2015, Alex <notifications@github.com> a écrit :
> I don't seem to be receiving any friend requests even though I sent some
to the account. Also I have added friends but when I call the getFriends
method, a blank array is returned.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/bXnLiqprMrEzrlWHcrnQJmhUKwdOlvFK7p7e45bXaQAzjD1a0vAn-191Lm9RU0ezYjGwpnJwTVS_QpKiSEBaO3rJsnw0LUsMQcc0MYdhegfZ-VxKQIWgSS6-xAC91DL4H7otc0yQxitOd6xOs9OLwId4UL92gA=s0-d-e1-ft#https://github.com/notifications/beacon/AAd6-iZBl7E7677dte0kyhLrCHXvNOLwks5nj9ydgaJpZM4DVW40.gif
>

**Comment by asmallgrin** [comment]
The getFriends method isn't using the right data.  add the following declarations:

    private JSONObject loginObj_friends;
    private static final String FRIENDS_RESPONSE_KEY = "friends_response";

then in setupLoginJSONObjects add:

  this.loginObj_friends = loginObj_full.getJSONObject(FRIENDS_RESPONSE_KEY);

then change the line in getFriends to:

  JSONArray friendsArr = this.loginObj_friends.getJSONArray(FRIENDS_KEY);

**Comment by hatboysam** [comment]
This library has been dead for a long time, officially closing all issues.
