### ISSUE TITLE
mvn assembly:assembly fails

### ISSUE THREAD

**Issue by rajeshkp** [hatboysam/JavaSnap#46]
[INFO] <<< maven-assembly-plugin:2.2-beta-5:assembly (default-cli) @ JavaSnap <<<
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:assembly (default-cli) @ JavaSnap ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.592s
[INFO] Finished at: Sun Feb 08 23:17:23 IST 2015
[INFO] Final Memory: 18M/369M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project JavaSnap: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by triple-take** [comment]
I've had this same issue, and spent the morning trying to learn maven and fix it. Turns out his readme just hasn't been updated yet. He's not using the maven-assembly-plugin anymore, just maven-shade-plugin. The way I was able to fix t his was by running this command instead:

    mvn clean compile package

this  cleans and compiles the shade jar with dependencies into the target folder, which you can then add to your project/IDE. If you're on eclipse, go to project properties > libraries > add external jar > browse to the snapchat build you'd like to use.

**Comment by liamcottle** [comment]
The code in this library is extremely old, and will lead to bans. Hence why
we haven't really updated anything.

**Comment by triple-take** [comment]
Yeah, I saw that its been around a while. Why will it lead to bans?

**Comment by liamcottle** [comment]
Snapchat are trying their best to block out third party apps.

And have changed their APIs etc, and not all code here is exact.

Plus, they recently changed their login again.

**Comment by triple-take** [comment]
That's really too bad. I guess it will help them manage spammers a little bit better. Could you add this into the readme? I spent a morning getting it up and running and building a bot. Cool project regardless, but if its going to be unusable soon it'd be good to know.

**Comment by triple-take** [comment]
I guess let me know when SnapLib is done haha - just noticed your repo
