### ISSUE TITLE
Sending snap

### ISSUE THREAD

**Issue by iBieel** [hatboysam/JavaSnap#49]
Well, I'm new to java and so I'm a little confused as to initialize the List <String> recipients? I'm starting up as a List but Snapchat.upload is in error.

**Comment by jamesst20** [comment]
Hi,

I don't think this library still works because of the new Snapchat
authentication

**Comment by iBieel** [comment]
Do you know if any still work?

**Comment by jamesst20** [comment]
Liam does have a private library (fork of this one) that still works and he
uses it for Casper (android app).

I don't know if he would like to share it

**Comment by liamcottle** [comment]
Correct, this project is old and no longer maintained.

I no longer use my fork of JavaSnap, and instead built my own library which
is Android specific.

To prevent SC from blocking my users, I must keep it private.

**Comment by liamcottle** [comment]
James, could you edit the Readme to state this lib is no longer working,
nor maintained. I don't have write access to this one.
