### ISSUE TITLE
Login returning "401 UNAUTHORIZED"

### ISSUE THREAD

**Issue by bharv410** [hatboysam/JavaSnap#50]
After editing the library slightly to work on Android I am getting these logs:

```
<html><head>
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: <meta http-equiv="content-type" content="text/html;charset=utf-8">
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: <title>401 UNAUTHORIZED</title>
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: </head>
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: <body text=#000000 bgcolor=#ffffff>
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: <h1>Error: UNAUTHORIZED</h1>
10-16 18:49:48.228 27241-27617/com.kigeniushq.myapplication V/benmark: </body></html>

```

sample code is : 

```
Snapchat snapchat = Snapchat.login("myrealusernamethatworks", "myrealpasswordthatworks");

            Friend[] friends = snapchat.getFriends();
            for (int i = 0; i < 5; i++) {
                Log.v("benmark", "friend = " + friends[i].getUsername());
            }

```

**Comment by Dannemannet** [comment]
I am also experiencing this problem, I tried using my own implementation for the login function to also work on Android. Only getting 401 UNAUTHORIZED

**Comment by jamesst20** [comment]
Hi,

The library is broken and I am not working anymore or it or it's not
planned at the moment.

Since new Snapchat login implementation with Google, this library cannot
authenticate.

**Comment by Dannemannet** [comment]
Oh ok, do you know of any changes, unofficial docs, libs etc. that could help getting it to work? What is this new implementation with google?

**Comment by jamesst20** [comment]
Hi,

It needs an authentication token from Google which is given by
authenticating with them.

I would recommend you to sniff the trafic of the official Snapchat app with
Fiddler and update the authentication change.

Thanks

**Comment by Dannemannet** [comment]
I see, I'll try that, thanks!

**Comment by jamesst20** [comment]
Alright, let me know how it goes :)

**Comment by Dannemannet** [comment]
Unfortunately I don't get it to work, Snapchat won't let me login while I monitor the traffic it seems, or if it's Googles authentication that doesn't allow it and thus snapchat fails.

**Comment by jamesst20** [comment]
Sounds right, I couldn't sniff the traffic aswell unlike I used to do it.

I remember having built a long while ago a patched APK of Snapchat that did print in logcat every request being sent to the server including parameters and user-agent.

Got some Smali skills ? :)

**Comment by Dannemannet** [comment]
Yes that could be one idea! Sorry, I don't know what Smali is. I could try decompile snapchats APK and see if it isnt to obfuscated, if you I understand how they are building their requests that way also

**Comment by jamesst20** [comment]
Smali is an accurate way to compile/decompile APK. If you decompile APK to java, you won't be able to edit and recompile.

Sadly, I tried, and it seems like I am unable to patch the APK. As soon as I decompile it and recompile it, even with no change applied, I am unable to log in to Snapchat.. :/

**Comment by jamesst20** [comment]
Hmmm it seems that what makes it fail is the apk signature. Taking the official apk, resigning it with signapk.jar --> adb install --> Can't sign in to Snapchat. I don't know if there is a possible workaround

**Comment by Dannemannet** [comment]
Hm, too bad. I haven't had any luck trying to find something right inside the source either

**Comment by jamesst20** [comment]
Check for LoginTask.java

I will try to figure out a solution but cannot guarantee anything

**Comment by Dannemannet** [comment]
Good, didn't noticed that before. Haven't gotten any wiser yet though...
Would help a lot if you found a solution!
I found a php library that still seems to be working, https://github.com/mgp25/SC-API
it seems like it uses some kind of middle API between snapchat and the client though. Are you familiar with this one? It could show that it atleast is possible to get it working

**Comment by jamesst20** [comment]
@Dannemannet 

Oh yeah it should be very easy to do. This API has been created by @liamcottle and I believe by what I understood that he made that API to access to Snapchat easily

**Comment by Dannemannet** [comment]
@jamesst20 I see! If you come up with a solution or find somewhere else I'd love it if you share! I don't have that much experience with this kind of hacking so I'm not sure I'll get this to work it seems

**Comment by jamesst20** [comment]
@Dannemannet 

Just checked out how the whole process was working. Forget about it, Google made it secure, the SHA-1 of the keystore must match with their API key hence why I can't patch an APK to do that. Since I am also unable to sniff the traffics anymore, it sounds like our only hope right now is reverse engineering Snapchat.

Otherwise use this if you want to make your life easier :) http://clients.casper.io/register.php

**Comment by Dannemannet** [comment]
Ah I see, too bad! I guess I could check out that and see if it could be a solution and let people who know their stuff better reverse engineer it if they want haha...
Thanks anyway for you time @jamesst20 :)

**Comment by manuelgu** [comment]
Any updates on this? 

@jamesst20 casper.io does not allow registration anymore :(

**Comment by jamesst20** [comment]
@manuelgu

No update yet, still in the progress. My reverse engineering skills still for native code need more skills before I am able to break up Snapchat.

**Comment by manuelgu** [comment]
Thanks for the quick reply and heads up!

**Comment by robipzo** [comment]
Maybe you can contact liam cottle to make faster progress?

**Comment by hatboysam** [comment]
This library has been dead for a long time, officially closing all issues.
