### ISSUE TITLE
Snapchat API

### ISSUE THREAD

**Issue by mzaboss** [hatboysam/JavaSnap#52]
looking for snapchat private API.

skype me at: mzaboss

**Comment by jamesst20** [comment]
You are looking for a Snapchat API or offering a Snapchat API?

**Comment by mzaboss** [comment]
Thank you for your reply.

I am looking for one.

**Comment by jamesst20** [comment]
I am already working on something. If it can go public, it will. In the mean time, have a look at Casper paid API.

Ticket closed

**Comment by liamcottle** [comment]
kek

**Comment by mzaboss** [comment]
Casper API is the best available. But As Mr. Liam mention in public, He's going to take it down. Liam is the greatest.
