### ISSUE TITLE
Logging in issues

### ISSUE THREAD

**Issue by gamer818** [hatboysam/JavaSnap#56]
I can't seem to log in to Snapchat, even when I provide the correct login information

The code I used:
`Snapchat sc = Snapchat.login(usernameLogin.getText(), passwordLogin.getText());

        if (sc != null) {
            System.out.println("Login Successful");
        } else {
            System.out.println("Login Failed");
        }`

sc always seems to be null.

**Comment by Logfro** [comment]
Thats because The lib ist deprecated due to snapchat changing their system.

**Comment by tjespe** [comment]
I have the same issue. Can we expect a fix?

**Comment by Logfro** [comment]
If someone finds a way how to fix it yes... but not probably in the near future

**Comment by StijnSimons** [comment]
Is it still dead?

**Comment by hatboysam** [comment]
This library has been dead for a long time, officially closing all issues.
